### PR TITLE
Improves projects UI and project navigation Closes #5

### LINKED ISSUE #5: Improve projects UI
Currently projects are cards at the bottom of the page. It looks all too similar to the other cards on the page.

A few suggestions:

Add an image to the project preview.
Make the cards bigger and display more information on them, like who built it, and what not
Improve the project page when you click on it, so it's easy to navigate back to the main site

### PR DESCRIPTION
**Pull request by sumana2001**
- Added an image to the project preview.
- Made the cards bigger and displayed more information on them with better UI and hover effects
- Created a back button for easy navigation
- Checked responsiveness

- [X] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.

https://user-images.githubusercontent.com/63084088/141231800-b823405e-f4db-45a4-8646-39ac7c9b6804.mov

https://user-images.githubusercontent.com/63084088/141231889-adc0603f-f3dc-4fda-a5ed-520493e6debe.mov

### CODE REVIEW

**Comment by grace-omotoso** [comment]
@sumana2001 project cards look good but I do not see the Back button on the project page. Also, the middle button on the project card which is supposed to be the project link is showing 404. Ideally, make that link the same link the users see when the card is clicked. 
For a better user experience, create a tooltip for the buttons on the project card. The first button can be "Youtube link", the second button can be "description", the third can be Github.

**Comment by sumana2001** [comment]
@grace-omotoso Thanks for the review. The back button is on the bottom-right corner of each project page. I'll fix the 404 error and add the tooltip immediately.

**Comment by grace-omotoso** [comment]
> @grace-omotoso Thanks for the review. The back button is on the bottom-right corner of each project page. I'll fix the 404 error and add the tooltip immediately.

@sumana2001 now I see it, my computer covered it. Please, move it to the right, that is a better user experience. Also, remember to add the tool tip. Looking forward to your updates. Thanks

**Comment by sumana2001** [comment]
@grace-omotoso I have added the tooltip and fixed the 404 error. The back button is already on the right corner, do you want me to take it even further or should I take it to the opposite side? If possible, could you share a screenshot of how it's looking on your local machine?

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
