### PR TITLE
Added navbar to the website [solves #4]

### PR DESCRIPTION
**Pull request by akshitadixit**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by Shubh4m-B** [comment]
@grace-omotoso , the changes that you suggested were implemented. But we have confusion regarding the Navbar animation on scroll part. Shall we get completely rid of that and make the Navbar already loaded on the top when the page loads or do u suggest something different.

**Comment by grace-omotoso** [comment]
@akshitadixit Please, fix merge conflicts

**Comment by grace-omotoso** [comment]
> @grace-omotoso , the changes that you suggested were implemented. But we have confusion regarding the Navbar animation on scroll part. Shall we get completely rid of that and make the Navbar already loaded on the top when the page loads or do u suggest something different.

Having just the navbar is fine. Another issue can be created for scroll functionality

**Comment by Shubh4m-B** [comment]
> > @grace-omotoso , the changes that you suggested were implemented. But we have confusion regarding the Navbar animation on scroll part. Shall we get completely rid of that and make the Navbar already loaded on the top when the page loads or do u suggest something different.
> 
> Having just the navbar is fine. Another issue can be created for scroll functionality

@grace-omotoso, Removed the scroll functionality, please take a look

**Comment by grace-omotoso** [comment]
@Shubh4m-B @akshitadixit nav bar is visible now but the images are distorte
nav_images_distorted
d.

**Comment by akshitadixit** [comment]
@grace-omotoso kindly check now

**Review by grace-omotoso — APPROVED** [review]

**Pull request merged**
